import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Helloworld from "@/components/helloworld";
import User from "@/components/User";
import Contador from "@/components/contador";
import Info2 from "@/components/Info2";


export default function Home() {
  return (
    <>
      <Head>
        <title>Meu primeiro site em react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Olá meu primeiro site em React!</h2>
      {/* Comentario no JSX*/}
      {/* Importanod o primeiro componente*/}
      <Helloworld />
      <User />
      <br />
      <Contador />
      <br />
      <Info2/>
    </>
  );
}
