import Head from "next/head";
import Semaforo from "@/components/Semaforo";


export default function Home() {
  return (
    <>
      <Head>
        <title>Meu primeiro site em react</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Semaforo />
      </main>
    </>
  );
}
